//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA.Connector.Redmine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public int Id { get; set; }
        public int JournalId { get; set; }
        public int PropertyId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Journal Journal { get; set; }
        public virtual JournalFacet Property { get; set; }
    }
}
