//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA.Connector.Redmine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
        public int Id { get; set; }
        public int IssueId { get; set; }
        public int RedmineId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Facet Author { get; set; }
        public virtual Issue Issue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
    }
}
