//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA.Connector.Redmine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int Id { get; set; }
        public int IssueId { get; set; }
        public string Text { get; set; }
        public int Count { get; set; }
    
        public virtual Issue Issue { get; set; }
    }
}
